### ISSUE TITLE
Plugin Failed to load

### ISSUE THREAD

**Issue by gitstar12** [RVillani/UE4Duino#2]
![untitled](https://user-images.githubusercontent.com/36403067/37120267-ec43d640-227f-11e8-9e73-db97f1239c47.png)

**Comment by Luckystrike561** [comment]
Same issue

**Comment by RVillani** [comment]
That happens when you try to use a code plugin in Unreal in a Blueprint-only project without the plugin's binaries built.
The solution is to either download the plugin with binaries or build it yourself by adding it to a code project (one that has a VS solution and a Source folder).

BTW, I have that wallpaper in Wallpaper Engine. It's gorgeous!
